version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test1
      - POSTGRES_USER=vasu
      - POSTGRES_PASSWORD=12341234

volumes:
  postgres_data: